Modify error resolution on cct commands on the QA upgrade job

diff --git a/jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml b/jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
--- a/jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
+++ b/jenkins/ci.suse.de/cloud-mkphyscloud-qa-test-upgrade-ui.yaml
@@ -98,6 +98,8 @@
             onadmin_zypper_patch_all
             onadmin_allow_vendor_change_at_nodes
 
+            # fail on errors on the next two steps
+            set -e
             export cct_tests=feature:ui:upgrade:landing+feature:ui:upgrade:admin:backup
             onadmin_run_cct
 
@@ -107,6 +109,8 @@
             export cct_tests=feature:ui:upgrade:admin:repos
             onadmin_run_cct
 
+            # do not fail on error in the last step
+            set +e
             # We only check if the upgrade screen is ready but we will do the upgrade via crowbarctl later
             export cct_tests=feature:ui:upgrade:admin:upgrade
             onadmin_run_cct
