jjb: submit-project refactoring and small fixes
Properly indent the code of this job.
Fixing small issues (eg. bash '[[ 4 > 30 ]]').
Consistently using double brackets.
Show error messages on error exit or skipping of items.

diff --git a/jenkins/ci.suse.de/openstack-submit-project.yaml b/jenkins/ci.suse.de/openstack-submit-project.yaml
--- a/jenkins/ci.suse.de/openstack-submit-project.yaml
+++ b/jenkins/ci.suse.de/openstack-submit-project.yaml
@@ -25,90 +25,83 @@
 
     builders:
       - shell: |
-          # DEBUG MODE with E=echo
-          # NORMAL MODE with E=
+          # to debug set E=echo
           E=
 
-          if [ -z "$starttime" ] ; then
+          if [[ ! $starttime ]] ; then
               echo "FATAL: calling script needs to specify starttime"
               exit 1
           fi
 
           case $subproject in
-          None) echo "No valid 'subproject' provided - defaults for safety reasons to 'None'"
-                exit 1
-          ;;
-          "-")  echo "Subproject set to '-': skip job, do not fail (eg. for Master project)"
-                exit 0
-          ;;
+              None) echo "No valid 'subproject' provided - defaults for safety reasons to 'None'"
+                    exit 1
+              ;;
+              "-")  echo "Subproject set to '-': skip job, do not fail (eg. for Master project)"
+                    exit 0
+              ;;
           esac
 
-          export BS=IBS
-          case $BS in
-          OBS)
-              OSC="osc -A https://api.opensuse.org"
-          ;;
-          IBS)
-              OSC="osc -A https://api.suse.de"
-          ;;
-          esac
-
+          BS=IBS
+          OSC="osc -A https://api.suse.de"
 
           COS=$project
           ECOS=""
           COSS=$COS:$subproject
-          export BS_CHECKOUT=/home/jenkins/${BS}_CHECKOUT/$COSS
+          BS_CHECKOUT=/home/jenkins/${BS}_CHECKOUT/$COSS
           submitcmd="$OSC copypac -K -e"
           OSCBUILDDIST=SLE_12_SP1
 
           case $project in
-          Devel:Cloud:6)
-              ECOS=systemsmanagement:crowbar:3.0
-          ;;
-          Devel:Cloud:6:SAP)
-              ECOS=systemsmanagement:crowbar:3.1
-          ;;
-          Devel:Cloud:7)
-              OSCBUILDDIST=SLE_12_SP2
-              ECOS=systemsmanagement:crowbar:4.0
-          ;;
-          Devel:Cloud:8)
-              OSCBUILDDIST=SLE_12_SP3
-              ECOS=systemsmanagement:crowbar:5.0
-          ;;
-          *) echo "Please add support for the project: $project"
-              exit 1
+              Devel:Cloud:6)
+                  ECOS=systemsmanagement:crowbar:3.0
+              ;;
+              Devel:Cloud:6:SAP)
+                  ECOS=systemsmanagement:crowbar:3.1
+              ;;
+              Devel:Cloud:7)
+                  OSCBUILDDIST=SLE_12_SP2
+                  ECOS=systemsmanagement:crowbar:4.0
+              ;;
+              Devel:Cloud:8)
+                  OSCBUILDDIST=SLE_12_SP3
+                  ECOS=systemsmanagement:crowbar:5.0
+              ;;
+              *) echo "Please add support for the project: $project"
+                  exit 1
           esac
 
+          pkg_filter=$(awk '$1=$1' <<< "${packagefilter}")
+          pkg_filter="${pkg_filter// /|}"
+          for component in `$OSC ls $COSS 2>/dev/null | grep -E "^(${pkg_filter})" | grep -v "^_product."` ; do
+              cd $BS_CHECKOUT
+              if [[ ! -d $component ]] ; then
+                  $OSC co -o $component $COSS $component
+              fi
+              cd $component
 
-          for COMPONENT in `$OSC ls $COSS 2>/dev/null | grep -E "^(${packagefilter// /|})" | grep -v "^_product."` ; do
-          cd $BS_CHECKOUT || exit 1
-          if [ ! -d $COMPONENT ] ; then
-              $OSC co -o $COMPONENT $COSS $COMPONENT
-          fi
-          cd $COMPONENT || exit 1
+              if ! grep -q "<linkinfo" .osc/_files ; then
+                  echo "Error: package $component in $subproject (staging) is not a link to non-staging."
+                  exit 2
+              fi
 
-          grep -q "<linkinfo" .osc/_files || exit 2
+              # avoid copying untested versions
+              lastchange=$($OSC api "source/$COSS/$component/_history" | perl -ne 'if(m/<time>(\d+)</) {print $1; exit 0}')
+              if [[ $lastchange -gt $starttime ]] ; then
+                  echo "Skipping $component due to a change after the test in the previous job started. test start time: $starttime :: last change: $lastchange"
+                  continue
+              fi
 
-          # avoid copying untested versions
-          lastchange=$($OSC api "source/$COSS/$COMPONENT/_history" | perl -ne 'if(m/<time>(\d+)</) {print $1; exit 0}')
-          if [[ $lastchange > $starttime ]] ; then
-              echo "skipping $COMPONENT because of a change after test started"
-              continue
-          fi
-
-          #  if $OSC rdiff $COS $COMPONENT $COSS | grep .  &&  $OSC api /build/$COSS/$OSCBUILDDIST/x86_64/$COMPONENT/_status | grep -E 'code="succeeded"|package="_product"'
-          if $OSC rdiff $COS $COMPONENT $COSS | grep .  && ( [ "$COMPONENT" = "_product" ] || $OSC r $COSS $COMPONENT -r $OSCBUILDDIST -a x86_64 | grep 'succeeded' )
-          then
-              # NOTE(saschpe): the "|| :" is a work-around for an osc bug (should be fixed, but Adrian needs to release a new osc)
-              # No need to put this in git.
-              [[ "$COMPONENT" =~ -doc$ ]] || {
-                  $E $submitcmd $COSS $COMPONENT $COS || :
-
-                  if [[ "$COMPONENT" =~ "crow" ]];  then
-                      [ -n "$ECOS" ] && $E $submitcmd $COSS $COMPONENT -t https://api.opensuse.org/ $ECOS || :
+              if $OSC rdiff $COS $component $COSS | grep .  && ( [ "$component" = "_product" ] || $OSC r $COSS $component -r $OSCBUILDDIST -a x86_64 | grep 'succeeded' )
+              then
+                  if [[ "$component" =~ -doc$ ]] ; then
+                      continue
                   fi
-              }
-          fi
-          done
 
+                  # submit package
+                  $E $submitcmd $COSS $component $COS || :
+                  if [[ $ECOS && $component =~ ^crowbar ]] ; then
+                      $E $submitcmd $COSS $component -t https://api.opensuse.org/ $ECOS || :
+                  fi
+              fi
+          done
