ardana-job: optionally reboot compute nodes before post-deploy checks
Add a new reboot_computes option to reboot all compute nodes before
running tempest and the rpm checks.  This will add a few minutes to
the run, so it's disabled by default.

Previously we were implicitly relying on set -e behaviour for aborting
immediately when site.yml fails.  This is somewhat obfuscated and
brittle, so also be more explicit about it.

diff --git a/jenkins/ci.suse.de/openstack-ardana.yaml b/jenkins/ci.suse.de/openstack-ardana.yaml
--- a/jenkins/ci.suse.de/openstack-ardana.yaml
+++ b/jenkins/ci.suse.de/openstack-ardana.yaml
@@ -59,6 +59,13 @@
             periodic-virtual, refstack, smoke, swift, tests2skip, tests-ci,
             upgrade-ci or upgrade
 
+      - bool:
+          name: reboot_computes
+          default: false
+          description: >-
+            Reboot compute nodes before running Tempest and other
+            post-deployment checks.
+
     builders:
       - shell: |
           set +x
@@ -177,9 +184,23 @@
                                        -e "deployer_model=${model}" \
                                        -e "verification_temp_dir=$verification_temp_dir" \
                                        init.yml
+
+          run_playbook_on_deployer () {
+              ssh $sshargs ardana@$DEPLOYER_IP \
+                  "cd ~/scratch/ansible/next/ardana/ansible ;
+                   ansible-playbook -v -i hosts/verb_hosts $1"
+          }
+
           # Run site.yml outside ansible for output streaming
-          ssh $sshargs ardana@$DEPLOYER_IP "cd ~/scratch/ansible/next/ardana/ansible ; \
-               ansible-playbook -vvv -i hosts/verb_hosts site.yml"
+          if ! run_playbook_on_deployer site.yml; then
+              echo "site.yml failed!  Aborting immediately." >&2
+              exit 1
+          fi
+
+          if ! run_playbook_on_deployer nova-compute-reboot.yml; then
+              echo "Reboot of compute nodes failed!  Aborting immediately." >&2
+              exit 1
+          fi
 
           ansible-playbook -v -i hosts -e "tempest_run_filter=${tempest_run_filter}" \
                                        -e "verification_temp_dir=$verification_temp_dir" \
