check devpts permissions

diff --git a/scripts/mkcloud b/scripts/mkcloud
--- a/scripts/mkcloud
+++ b/scripts/mkcloud
@@ -38,6 +38,14 @@ if [ ! -e $CVOL ] ; then
   echo "Please set the cloud volume group: export CVOL=/dev/sdx"
   exit 93
 fi
+
+if grep "devpts.*mode=.00" /proc/mounts ; then
+  echo "Error: /dev/pts is not accessible for libvirt, maybe you use autobuild on your system."
+  echo "Please remount it using the following command:"
+  echo " # mount -o remount,mode=620,gid=5 devpts -t devpts /dev/pts"
+  exit 13
+fi
+
 precleanup=true
 adminip=192.168.124.10
 
