syncSLErepos: Introduce a SITE variable
SITE can be set to "nue" (Nuermberg) or "prv" (Provo). Depending on
that var, different mirrors are used to sync the repositories. This is
useful for people outside from europe.
Note: Currently only the content from dist/ibs recognizes $SITE.

diff --git a/hostscripts/clouddata/syncSLErepos b/hostscripts/clouddata/syncSLErepos
--- a/hostscripts/clouddata/syncSLErepos
+++ b/hostscripts/clouddata/syncSLErepos
@@ -1,5 +1,23 @@
 #!/bin/bash
 
+# SITE to use. Can be "nue" or "prv" (Nuermberg and Provo)
+: ${SITE:="nue"}
+
+if [ $SITE = "nue" ]; then
+    # Currently /mnt/dist can be setup via: "mount dist.nue.suse.com:/dist /mnt/dist/"
+    ibs_source="/mnt/dist/ibs/"
+    # FIXME(toabctl): use rsync for ibs_source and install_source when
+    # https://infra.nue.suse.com/SelfService/Display.html?id=90326 is fixed
+    #ibs_source="rsync://dist.suse.de/ibs/"
+    #install_source="/mnt/dist/install/"
+elif [ $SITE = "prv" ]; then
+    ibs_source="rsync://ibs-mirror.prv.suse.net/dist/ibs/"
+    #install_source="rsync://ibs-mirror.prv.suse.net/dist/install/"
+else
+    echo "Invalid site $SITE"
+    exit 1
+fi
+
 # disable/debug rsync with E=echo
 E=echo
 E=
@@ -16,8 +34,7 @@ rsync="$E rsync $DRY --bwlimit 10000 --delay-updates --delete-delay -avH --no-ow
 
 # http://download.suse.de/ibs/Devel:/Cloud:/4/images/*qcow2 -> images/SLES11-SP3-x86_64-cfntools.qcow2
 
-buildsuse=/mnt/dist/ibs/
-ibsmaint=$buildsuse/SUSE\:/Maintenance\:/Test\:/
+ibsmaint=${ibs_source}/SUSE\:/Maintenance\:/Test\:/
 
 ##############
 # SLE 12
@@ -54,14 +71,14 @@ for servicepack in 1 2 3; do
         destdir_sles_pool=/srv/nfs/repos/$arch/SLES$repo_version-Pool/
         mkdir -p $destdir_sles_pool
         if [ -z "$sync_from_ibs" ]; then
-            $rsync --link-dest /srv/nfs/suse-${chef_version}${install_subdir}/install/suse/ $buildsuse/SUSE/Products/SLE-SERVER/$version/$arch/product/ $destdir_sles_pool
+            $rsync --link-dest /srv/nfs/suse-${chef_version}${install_subdir}/install/suse/ ${ibs_source}/SUSE/Products/SLE-SERVER/$version/$arch/product/ $destdir_sles_pool
         else
             $rsync --link-dest /srv/nfs/suse-${chef_version}${install_subdir}/install/suse/ /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-Server-POOL-$arch-Media1/ $destdir_sles_pool
         fi
         # SLES updates
         destdir_sles_updates=/srv/nfs/repos/$arch/SLES$repo_version-Updates/
         mkdir -p $destdir_sles_updates
-        $rsync $buildsuse/SUSE/Updates/SLE-SERVER/$version/$arch/update/ $destdir_sles_updates
+        $rsync ${ibs_source}/SUSE/Updates/SLE-SERVER/$version/$arch/update/ $destdir_sles_updates
         # SLES test updates
         if test -d $ibsmaint/SLE-SERVER\:/$version\:/$arch/update/ ; then
             destdir_sles_updates_test=/srv/nfs/repos/$arch/SLES$repo_version-Updates-test/
@@ -75,14 +92,14 @@ for servicepack in 1 2 3; do
             destdir_ha_pool=/srv/nfs/repos/$arch/SLE$repo_version-HA-Pool/
             mkdir -p $destdir_ha_pool
             if [ -z "$sync_from_ibs" ]; then
-                $rsync $buildsuse/SUSE/Products/SLE-HA/$version/$arch/product/ $destdir_ha_pool
+                $rsync ${ibs_source}/SUSE/Products/SLE-HA/$version/$arch/product/ $destdir_ha_pool
             else
                 $rsync /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-HA-POOL-$arch-Media1/ $destdir_ha_pool
             fi
             # HA updates
             destdir_ha_updates=/srv/nfs/repos/$arch/SLE$repo_version-HA-Updates/
             mkdir -p $destdir_ha_updates
-            $rsync $buildsuse/SUSE/Updates/SLE-HA/$version/$arch/update/ $destdir_ha_updates
+            $rsync ${ibs_source}/SUSE/Updates/SLE-HA/$version/$arch/update/ $destdir_ha_updates
             # HA test updates
             if test -d $ibsmaint/SLE-HA\:/$version\:/$arch/update/ ; then
                 destdir_ha_updates_test=/srv/nfs/repos/$arch/SLE$repo_version-HA-Updates-test/
@@ -97,14 +114,14 @@ for servicepack in 1 2 3; do
             destdir_sdk_pool=/srv/nfs/repos/$arch/SLE$repo_version-SDK-Pool/
             mkdir -p $destdir_sdk_pool
             if [ -z "$sync_from_ibs" ]; then
-                $rsync $buildsuse/SUSE/Products/SLE-SDK/$version/$arch/product/ $destdir_sdk_pool
+                $rsync ${ibs_source}/SUSE/Products/SLE-SDK/$version/$arch/product/ $destdir_sdk_pool
             else
                 $rsync /mnt/dist/ibs/SUSE\:/SLE-$version\:/GA/images/repo/SLE-$version-SDK-POOL-$arch-Media1/ $destdir_sdk_pool
             fi
             # SDK updates
             destdir_sdk_updates=/srv/nfs/repos/$arch/SLE$repo_version-SDK-Updates/
             mkdir -p $destdir_sdk_updates
-            $rsync $buildsuse/SUSE/Updates/SLE-SDK/$version/$arch/update/ $destdir_sdk_updates
+            $rsync ${ibs_source}/SUSE/Updates/SLE-SDK/$version/$arch/update/ $destdir_sdk_updates
             # SDK test updates
             if test -d $ibsmaint/SLE-SDK\:/$version\:/$arch/update/ ; then
                 destdir_sdk_updates_test=/srv/nfs/repos/$arch/SLE$repo_version-SDK-Updates-test/
@@ -132,16 +149,16 @@ for version in 2.1 4 5; do
         if [[ $version == 4 ]]; then
             poolsource=/mnt/dist/ibs/SUSE\:/SLE-12-SP2\:/Update\:/Products\:/SES${version}/images/repo/SUSE-Enterprise-Storage-${version}-POOL-${arch}-Media1/
         else
-            poolsource=$buildsuse/SUSE/Products/Storage/$version/$arch/product/
+            poolsource=${ibs_source}/SUSE/Products/Storage/$version/$arch/product/
         fi
         destdir_ses_pool=/srv/nfs/repos/$arch/SUSE-Enterprise-Storage-$version-Pool
         mkdir -p $destdir_ses_pool
         $rsync $poolsource $destdir_ses_pool
 
-        if test -d $buildsuse/SUSE/Updates/Storage/$version/$arch/update/; then
+        if test -d ${ibs_source}/SUSE/Updates/Storage/$version/$arch/update/; then
             destdir_ses_updates=/srv/nfs/repos/$arch/SUSE-Enterprise-Storage-$version-Updates
             mkdir -p $destdir_ses_updates
-            $rsync $buildsuse/SUSE/Updates/Storage/$version/$arch/update/ $destdir_ses_updates
+            $rsync ${ibs_source}/SUSE/Updates/Storage/$version/$arch/update/ $destdir_ses_updates
         fi
 
         if test -d $ibsmaint/Storage\:/$version\:/$arch/update/; then
@@ -193,16 +210,16 @@ for version in 6 7 8; do
         mount_and_rsync "/mnt/dist/ibs/Devel\:/Cloud\:/$version/images/iso/SUSE-OPENSTACK-CLOUD-$version-$arch-Build[0-9][0-9][0-9][0-9]-Media1.iso" $arch/SUSE-OpenStack-Cloud-$version-devel
         mount_and_rsync "/mnt/dist/ibs/Devel\:/Cloud\:/$version\:/Staging/images/iso/SUSE-OPENSTACK-CLOUD-$version-$arch-Build[0-9][0-9][0-9][0-9]-Media1.iso" $arch/SUSE-OpenStack-Cloud-$version-devel-staging
 
-        if test -d $buildsuse/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ ; then
+        if test -d ${ibs_source}/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ ; then
             destdir_cloud_pool=/srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-Pool/
             mkdir -p $destdir_cloud_pool
-            $rsync $buildsuse/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ $destdir_cloud_pool
+            $rsync ${ibs_source}/SUSE/Products/OpenStack-Cloud/$version/$arch/product/ $destdir_cloud_pool
         fi
 
-        if test -d $buildsuse/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ ; then
+        if test -d ${ibs_source}/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ ; then
             destdir_cloud_updates=/srv/nfs/repos/$arch/SUSE-OpenStack-Cloud-$version-Updates/
             mkdir -p $destdir_cloud_updates
-            $rsync $buildsuse/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ $destdir_cloud_updates
+            $rsync ${ibs_source}/SUSE/Updates/OpenStack-Cloud/$version/$arch/update/ $destdir_cloud_updates
         fi
 
         if test -d $ibsmaint/OpenStack-Cloud\:/$version\:/$arch/update/; then
