Ensure that syncSLErepos syns hourly again
As the last entry always failed, the lock wasn't removed
and which caused the sync to stall for the timeout (4 hours) to
happen. by ensuring that the sync is finishing successfully
it happens more regularly again.

diff --git a/hostscripts/clouddata/syncSLErepos b/hostscripts/clouddata/syncSLErepos
--- a/hostscripts/clouddata/syncSLErepos
+++ b/hostscripts/clouddata/syncSLErepos
@@ -296,7 +296,8 @@ if [ $SITE = "nue" ]; then
         rsync_with_create rsync://rsync.opensuse.org/buildservice-repos/$obsrepo/ /srv/nfs/repos/repositories/$obsrepo/
     done
 
-    timeout 1h ~/bin/syncgitrepos
+    # this one is always failing - we need to ignore that otherwise the lock file remains stuck
+    timeout 1h ~/bin/syncgitrepos || :
 fi
 
 rm -f $lockf
